### ISSUE TITLE
Hoe to Add animation in the custom layout view element

### ISSUE THREAD

**Issue by Rahulrsannidhi** [OuTlAnDeR24/ShowcaseView#2]
Hi am using your library  for tutorial view in my application its very helpful.very easy to use.
How can i add a animation to the view element inside the custom view (like TextView or ImageView ) I tried lot can you please help on this.
Also when find the view element in the custom view using inflate layout to  set text and all not working.

**Comment by outlander24** [comment]
@Rahulrsannidhi The views are getting drawn on the canvas and aren't getting inflated. So, you won't get any view objects with you as such. Hence, applying animations or setting text during run-time isn't possible. Thanks!
