### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by rhonyabdullah** [OuTlAnDeR24/ShowcaseView#5]
Hello, i found this error on xiaomi redmi note 4 with nougat OS version through `fabric crashlytics`, any help ?

Fatal Exception: java.lang.IllegalStateException
The specified child already has a parent. You must call removeView() on the child's parent first.

```
ShowcaseViewBuilder.addShowcaseView (ShowcaseViewBuilder.java:246)
ShowcaseViewBuilder.access$000 (ShowcaseViewBuilder.java:31)
ShowcaseViewBuilder$1.onGlobalLayout (ShowcaseViewBuilder.java:233)
```

**Comment by outlander24** [comment]
@rhonyabdullah 
Could you also post the snippet in which you're building the ShowcaseView and showing it? 
Also, in which lifecycle method are you trying to showcase?

**Comment by rhonyabdullah** [comment]
Sorry for late reponse,
It was happened here, [oGlobalLayout](https://github.com/outlander24/ShowcaseView/blob/master/showcaseview/src/main/java/outlander/showcaseview/ShowcaseViewBuilder.java#L224)

So i'm change `onGlobalLayout()` into something like this;
```
public void onGlobalLayout() {
                        invalidate();
                        addShowcaseView();
                        if (android.os.Build.VERSION.SDK_INT <= Build.VERSION_CODES.JELLY_BEAN) {
                            mTargetView.getViewTreeObserver().removeGlobalOnLayoutListener(this);
                        } else {
                            mTargetView.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                        }
                    }
```

Now, i'm just waiting for the result on fabric.

**Comment by outlander24** [comment]
@rhonyabdullah Did you try updating the library?

**Comment by rhonyabdullah** [comment]
Ok updated.
